### ISSUE TITLE
adding .gitignore for future task / project 

### ISSUE THREAD

**Issue by amirisback** [Fuadafdhal/Treasure#1]
*.iml
/.gradle
.gradle
.idea
/local.properties
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
.DS_Store
build
/build
/captures
.externalNativeBuild

built application files
.apk
.ap_

files for the dex VM
*.dex

Java class files
*.class

generated files
bin/
gen/
.externalNativeBuild/

Local configuration file (sdk path, etc)
local.properties
app/version.properties

**Comment by Fuadafdhal** [comment]
maksudnya bagaimana tuh bang hehe 😅😅

**Comment by amirisback** [comment]
https://github.com/Fuadafdhal/Treasure/blob/master/.gitignore 

di bagian sini, coba replace yang diatas. 
buat ngehapus settingan android studiomu (.idea)
jadi kalo orang nge pull ga conflict

**Comment by Fuadafdhal** [comment]
ooow seperti itu yah... masih kurang tau sih hehe 😅 jadi langsung replace yang di atas aja yah?

**Comment by amirisback** [comment]
iya bro
